name: GitHub CI

on: [push]

jobs:
  build-and-test:
    uses: ./.github/workflows/testing.yml
    with:
      petals_branch: ${{ github.ref }}
    permissions:
      # For publishing results
      checks: write  
